### ISSUE TITLE
Configurar entorno con Vite y GitHub Actions

### ISSUE THREAD

**Issue by dangarbar** [dangarbar/portfolio-react#1]
Inicializar el proyecto con Vite y configurar GitHub Actions para CI/CD.

**Comment by dangarbar** [comment]
# 🚀 Configurar entorno con Vite y GitHub Actions

## 📌 Objetivo  
Inicializar un proyecto en **React 18** utilizando **Vite** para un entorno rápido y moderno. Además, configurar **GitHub Actions** para automatizar pruebas y despliegue en Vercel.  

---

## 🔹 Pasos para completar la tarea  

### 1️⃣ Crear el Proyecto con Vite  
Ejecuta el siguiente comando para crear el proyecto con Vite y la plantilla de React:

```bash
npm create vite@latest portfolio-react --template react
```
📌 Esto generará una estructura de archivos optimizada para React con Vite.  

Accede a la carpeta del proyecto y **instala las dependencias**:

```bash
cd portfolio-react
npm install
```

Para verificar que todo funciona correctamente, inicia el servidor de desarrollo:

```bash
npm run dev
```
Esto abrirá la aplicación en `http://localhost:5173/`.

---

### 2️⃣ Configurar el repositorio en GitHub  
Dentro de la carpeta del proyecto, inicializa **Git** y realiza el primer commit:

```bash
git init
git add .
git commit -m "🚀 Configuración inicial del proyecto con Vite"
```

Luego, vincula el repositorio en GitHub y sube los cambios:

```bash
git branch -M main
git remote add origin https://github.com/dangarbar/portfolio-react.git
git push -u origin main
```

Verifica que el código está subido correctamente en:  
🔗 [https://github.com/dangarbar/portfolio-react](https://github.com/dangarbar/portfolio-react)

---

### 3️⃣ Configurar GitHub Actions para CI/CD  
📌 **Objetivo:** Crear un workflow en GitHub Actions que realice pruebas y despliegue en Vercel.

Crea la carpeta de configuración de workflows:

```bash
mkdir -p .github/workflows
```

Crea el archivo de workflow para CI/CD en `.github/workflows/deploy.yml`:

```yaml
name: Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🔍 Ejecutar pruebas
        run: npm test

      - name: 🏗 Construir la aplicación
        run: npm run build

      - name: 🚀 Desplegar en Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
```

---

### 4️⃣ Configurar el Token de Vercel en GitHub  
1️⃣ Ve a **Vercel**: [https://vercel.com/account/tokens](https://vercel.com/account/tokens)  
2️⃣ Genera un **nuevo token** y cópialo.  
3️⃣ Ve a **GitHub → Settings → Secrets and variables → Actions → New repository secret**.  
4️⃣ Crea una variable llamada **`VERCEL_TOKEN`** y pega el token generado.  

📌 **Este token permite a GitHub Actions desplegar la aplicación automáticamente en Vercel.**

---

### 5️⃣ Configurar Prettier y ESLint  
📌 Para mantener un código limpio, instala **Prettier** y **ESLint**:

```bash
npm install --save-dev eslint prettier eslint-config-prettier eslint-plugin-prettier
```

Configura `.eslintrc.json`:

```json
{
  "extends": ["eslint:recommended", "plugin:react/recommended", "prettier"],
  "plugins": ["react", "prettier"],
  "rules": {
    "prettier/prettier": "error",
    "react/prop-types": "off"
  }
}
```

Configura `.prettierrc`:

```json
{
  "singleQuote": true,
  "semi": false,
  "trailingComma": "none"
}
```

---

## 📌 Criterios de finalización de la tarea  
✅ **El proyecto de React con Vite está inicializado y funciona correctamente.**  
✅ **El código está subido al repositorio en GitHub.**  
✅ **El workflow de GitHub Actions está configurado correctamente.**  
✅ **Vercel despliega la aplicación automáticamente.**  
✅ **ESLint y Prettier están configurados para mantener buenas prácticas.**
