### ISSUE TITLE
Configurar despliegue en Vercel con GitHub Actions

### ISSUE THREAD

**Issue by dangarbar** [dangarbar/portfolio-react#8]
Automatizar el despliegue de la aplicación en Vercel mediante GitHub Actions.

**Comment by dangarbar** [comment]
# 🚀 Configurar despliegue en Vercel con GitHub Actions

## 📌 Objetivo  
Automatizar el despliegue de la aplicación en **Vercel** utilizando **GitHub Actions**, asegurando una integración continua eficiente.

---

## 🔹 Pasos para completar la tarea  

### 1️⃣ Instalar la CLI de Vercel  
Ejecuta el siguiente comando para instalar la CLI de Vercel:  

```bash
npm install -g vercel
```

Inicia sesión en Vercel:  

```bash
vercel login
```

Configura el proyecto con:  

```bash
vercel
```

📌 Esto generará un archivo `.vercel` en tu proyecto con la configuración de despliegue.

---

### 2️⃣ Configurar el Token de Vercel en GitHub  
1. Accede a [Vercel Tokens](https://vercel.com/account/tokens) y genera un nuevo token.  
2. En GitHub, ve a **Settings → Secrets and variables → Actions → New repository secret**.  
3. Crea una variable llamada **`VERCEL_TOKEN`** y pega el token generado.  

---

### 3️⃣ Crear el workflow de GitHub Actions  
Crea la carpeta de workflows en el proyecto:  

```bash
mkdir -p .github/workflows
```

Crea el archivo `.github/workflows/deploy.yml`:  

```bash
touch .github/workflows/deploy.yml
```

Agrega la siguiente configuración a `deploy.yml`:  

```yaml
name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🏗 Construir la aplicación
        run: npm run build

      - name: 🚀 Desplegar en Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
```

---

### 4️⃣ Realizar un push para activar el despliegue  
Confirma los cambios y súbelos a GitHub:  

```bash
git add .
git commit -m "🚀 Configuración de despliegue automático en Vercel"
git push origin main
```

Esto activará el workflow y desplegará automáticamente la aplicación en **Vercel**.

---

## 📌 Criterios de finalización de la tarea  
✅ **El proyecto está configurado en Vercel y GitHub.**  
✅ **El token de Vercel está almacenado en GitHub Secrets.**  
✅ **El workflow de GitHub Actions automatiza el despliegue en Vercel.**  
✅ **Un push a `main` activa el despliegue automáticamente.**  
✅ **Los cambios están subidos al repositorio en GitHub.**
